// <auto-generated />
using BMC_baithi2324.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMC_baithi2324.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240619083233_create_table_Person")]
    partial class create_table_Person
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("BMC_baithi2324.Models.Person", b =>
                {
                    b.Property<string>("Hovaten")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Masinhvien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Hovaten");

                    b.ToTable("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
