// <auto-generated />
using BMC_baithi2324.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMC_baithi2324.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("BMC_baithi2324.Models.Person", b =>
                {
                    b.Property<string>("Hovaten")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Masinhvien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Hovaten");

                    b.ToTable("Persons");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BMC_baithi2324.Models.Employee", b =>
                {
                    b.HasBaseType("BMC_baithi2324.Models.Person");

                    b.Property<string>("Love")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Masv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BMC_baithi2324.Models.Employee", b =>
                {
                    b.HasOne("BMC_baithi2324.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("BMC_baithi2324.Models.Employee", "Hovaten")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
